import React, { useState } from "react";
import { useMutation, useQuery } from "@apollo/client/react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import AcademyShell from "./AcademyShell";
import { academyError, BEGIN_LEARNER_ACCOUNT, PUBLIC_ACADEMY_COURSES } from "./academyFlow";

export default function AcademyRegister() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const courseId = params.get("course");
  const { data, loading } = useQuery(PUBLIC_ACADEMY_COURSES); const [begin, { loading: saving }] = useMutation(BEGIN_LEARNER_ACCOUNT);
  const [email, setEmail] = useState(""); const [byu, setByu] = useState(false); const [error, setError] = useState("");
  const course = data?.publicAcademyCourses?.find((item) => item.id === courseId);
  const submit = async (event) => { event.preventDefault(); if (!courseId) return setError("Choose a course before registering."); try { setError(""); const { data: result } = await begin({ variables: { input: { courseId, email } } }); sessionStorage.setItem("katelAcademyApplication", JSON.stringify({ applicantId: result.beginAcademyLearnerAccount.subjectId, email: result.beginAcademyLearnerAccount.email, courseId, isByu: byu })); navigate("/academy/verify-email"); } catch (err) { setError(academyError(err)); } };
  return <AcademyShell title="Verify your email to begin" description="Your email is your Academy identity until payment. No learner portal account is created at this stage."><div className="mx-auto max-w-2xl rounded-3xl bg-white p-6 shadow-xl ring-1 ring-slate-200 md:p-10"><div className="mb-7 rounded-2xl bg-blue-50 p-4 text-sm text-slate-700">{loading ? "Loading course…" : course ? <><strong>{course.title}</strong><br />{course.durationWeeks} week{course.durationWeeks === 1 ? "" : "s"} · {course.code}</> : <>No course selected. <Link className="font-bold text-[#003F8E] underline" to="/academy">Choose a course</Link>.</>}</div><form onSubmit={submit} className="space-y-5"><label className="block text-sm font-semibold text-slate-700">Email address<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" /></label><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm text-slate-700"><input type="checkbox" checked={byu} onChange={(e)=>setByu(e.target.checked)} className="mt-1" /><span><strong>Request the BYU Pathway fee</strong><br /><span className="text-slate-500">After email verification, you will upload proof for review. Otherwise you proceed directly to payment.</span></span></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving || !course} className="w-full rounded-xl bg-[#003F8E] px-5 py-3.5 font-bold text-white disabled:opacity-50">{saving ? "Sending verification code…" : "Send verification code"}</button></form></div></AcademyShell>;
}
