import React, { useState } from "react";
import { useMutation } from "@apollo/client/react";
import { useNavigate, useSearchParams } from "react-router-dom";
import AcademyShell from "./AcademyShell";
import { academyError, ACTIVATE_ACADEMY_APPLICANT } from "./academyFlow";
import { useAuth } from "../../features/auth/AuthProvider";
import { Eye, EyeOff } from "lucide-react";

export default function AcademyActivate() {
  const navigate = useNavigate(); const { login } = useAuth(); const [params] = useSearchParams(); const token = params.get("token") || "";
  const [form, setForm] = useState({ firstName: "", lastName: "", password: "", confirmPassword: "" }); const [error, setError] = useState(""); const [showPassword, setShowPassword] = useState(false); const [showConfirmation, setShowConfirmation] = useState(false);
  const [activate, { loading }] = useMutation(ACTIVATE_ACADEMY_APPLICANT);
  const submit = async (event) => { event.preventDefault(); if (!token) return setError("This activation link is missing or invalid."); if (form.password !== form.confirmPassword) return setError("Passwords do not match."); try { setError(""); await activate({ variables: { input: { token, firstName: form.firstName, lastName: form.lastName, password: form.password } } }); const email = params.get("email"); if (email) await login(email, form.password); navigate("/portal/academy", { replace: true }); } catch (err) { setError(academyError(err)); } };
  return <AcademyShell title="Activate your Academy account" description="Payment is confirmed. Finish your portal account with your name and password to begin learning."><form onSubmit={submit} className="mx-auto grid max-w-xl gap-5 rounded-3xl bg-white p-7 shadow-xl ring-1 ring-slate-200 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Verified email<p className="mt-2 rounded-xl bg-slate-50 px-4 py-3 font-normal text-slate-700">{params.get("email") || "Verified Academy email"}</p></label><label className="text-sm font-semibold text-slate-700">First name<input required value={form.firstName} onChange={(e)=>setForm({...form,firstName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3" /></label><label className="text-sm font-semibold text-slate-700">Last name<input required value={form.lastName} onChange={(e)=>setForm({...form,lastName:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Create password<div className="relative mt-2"><input required minLength="12" type={showPassword ? "text" : "password"} value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} className="w-full rounded-xl border px-4 py-3 pr-12" /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={()=>setShowPassword(!showPassword)} className="absolute inset-y-0 right-3 text-slate-500 hover:text-[#003F8E]">{showPassword ? <EyeOff size={19} /> : <Eye size={19} />}</button></div></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Confirm password<div className="relative mt-2"><input required minLength="12" type={showConfirmation ? "text" : "password"} value={form.confirmPassword} onChange={(e)=>setForm({...form,confirmPassword:e.target.value})} className="w-full rounded-xl border px-4 py-3 pr-12" /><button type="button" aria-label={showConfirmation ? "Hide password confirmation" : "Show password confirmation"} onClick={()=>setShowConfirmation(!showConfirmation)} className="absolute inset-y-0 right-3 text-slate-500 hover:text-[#003F8E]">{showConfirmation ? <EyeOff size={19} /> : <Eye size={19} />}</button></div></label>{error && <p className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="sm:col-span-2 rounded-xl bg-[#003F8E] py-3.5 font-bold text-white disabled:opacity-50">{loading ? "Activating…" : "Create account and open Academy"}</button></form></AcademyShell>;
}
