import React, { useState } from "react";
import { useMutation } from "@apollo/client/react";
import { useNavigate, useSearchParams } from "react-router-dom";
import AcademyShell from "./AcademyShell";
import { academyError, BEGIN_BYU, VERIFY_BYU } from "./academyFlow";

export default function AcademyByuVerification() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const courseId = params.get("course");
  const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [request, setRequest] = useState(null); const [error, setError] = useState("");
  const [begin, { loading: sending }] = useMutation(BEGIN_BYU); const [verify, { loading: verifying }] = useMutation(VERIFY_BYU);
  const send = async (event) => { event.preventDefault(); try { setError(""); const { data } = await begin({ variables: { input: { email } } }); setRequest(data.beginByuPathwayVerification); } catch (err) { setError(academyError(err)); } };
  const confirm = async (event) => { event.preventDefault(); try { setError(""); const { data } = await verify({ variables: { input: { verificationId: request.subjectId, code } } }); sessionStorage.setItem("katelByuProofGrant", JSON.stringify({ ...data.verifyByuPathwayEmail, courseId, email: request.email, developmentCode: request.developmentCode })); navigate("/academy/byu-upload"); } catch (err) { setError(academyError(err)); } };
  return <AcademyShell title="Request the BYU Pathway fee" description="This is separate from your portal account. Verify the email you control, submit proof, then an authorized reviewer decides the request."><div className="mx-auto max-w-xl rounded-3xl bg-white p-7 shadow-xl ring-1 ring-slate-200">{!request ? <form onSubmit={send} className="space-y-5"><label className="block text-sm font-semibold text-slate-700">Email address<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" /></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={sending} className="w-full rounded-xl bg-[#003F8E] py-3.5 font-bold text-white">{sending ? "Sending code…" : "Send verification code"}</button></form> : <form onSubmit={confirm} className="space-y-5"><p className="text-slate-600">We sent a code to <strong>{request.email}</strong>.</p><input required maxLength="6" inputMode="numeric" value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,""))} className="w-full rounded-xl border px-4 py-4 text-center text-2xl tracking-[.4em]" placeholder="000000" />{request.developmentCode && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Development code: <strong>{request.developmentCode}</strong></p>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={verifying} className="w-full rounded-xl bg-[#003F8E] py-3.5 font-bold text-white">{verifying ? "Verifying…" : "Verify and continue"}</button></form>}</div></AcademyShell>;
}
