import React, { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import AcademyShell from "./AcademyShell";

const apiBase = (import.meta.env.VITE_GRAPHQL_URL || "http://localhost:3000/graphql").replace(/\/graphql$/, "");
export default function AcademyByuUpload() {
  const navigate = useNavigate(); const grant = useMemo(() => { try { return JSON.parse(sessionStorage.getItem("katelByuProofGrant") || "null"); } catch { return null; } }, []);
  const [file, setFile] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!grant) return navigate("/academy/byu-verification", { replace: true }); if (!file) return setError("Choose a PDF or image proof document."); try { setError(""); setLoading(true); const body = new FormData(); body.append("file", file); body.append("verificationId", grant.verificationId); body.append("submissionToken", grant.submissionToken); const response = await fetch(`${apiBase}/uploads/byu-proof`, { method: "POST", body }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "Proof upload failed."); sessionStorage.removeItem("katelByuProofGrant"); navigate("/academy/byu-review"); } catch (err) { setError(err.message || "Proof upload failed."); } finally { setLoading(false); } };
  return <AcademyShell title="Submit BYU Pathway proof" description="Your document is compressed safely when appropriate, stored separately from a portal account, and sent to the authorized review queue."><form onSubmit={submit} className="mx-auto max-w-xl rounded-3xl bg-white p-7 shadow-xl ring-1 ring-slate-200"><input required accept="image/jpeg,image/png,image/webp,application/pdf" type="file" onChange={(e)=>setFile(e.target.files?.[0] || null)} className="w-full rounded-xl border p-3" />{file && <p className="mt-3 text-sm text-slate-600">Selected: {file.name}</p>}<p className="mt-4 text-sm leading-6 text-slate-500">Accepted: PDF, JPG, PNG or WebP. Maximum 10 MB.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-[#003F8E] py-3.5 font-bold text-white disabled:opacity-50">{loading ? "Uploading proof…" : "Submit proof for review"}</button></form></AcademyShell>;
}
